added old scripts (issue #1)
intuitive-robots/irl_polymetis pull request #8
Opened 2024-03-20 12:24 UTC by ploedige

Fixes issue #1 .

## Changes proposed:

- add old scripts to scripts folder

2024-03-20 12:38 UTC, LiXiling requested changes
I think mainly a comment for the rest pose in 201. Then i will approve the PR.

2024-03-20 12:38 UTC, LiXiling commented on scripts/start_robot_201.sh
is the rest_pose specific to the kitchen robot? Maybe add a comment.

also: we check for / auto activate a conda env named "polymetis". I guess this is specific to our hardware setup. but maybe this is a good chance to check if the README mentions somewhere, that we want our env to be called `polymetis`.

2024-03-21 09:24 UTC, ploedige commented
> Also, a little bit more detail in the PR description would be appreciated :D

Added more information to the PR description

2024-03-21 09:34 UTC, ploedige commented
Removed the initial pose. Since robot 201 is not part of the kitchen environment, there is no reason for the initial pose.

Regarding the documentation:
Starting the server is not mentioned Readme at all. This should be part of  issue #3.

Also:
The start scripts should be unified into one script that accesses the hydra configuration file for the robots.
That is how I have done it in my thesis program. For this another issue should be added

2024-03-21 11:54 UTC, LiXiling approved these changes

2024-03-21 11:54 UTC, merged